name: Build & test

on:
  push:
    branches:
    - trying
    - staging
    # Until support to verify master branch integrity
    - master
    tags: '**'
  pull_request:
    branches:
    - master
    - 'feature/**'
    - 'release/**'

env:
  CARGO_TERM_COLOR: always
  # Enable sccache build optimization
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  build:
    name: 🚀 Build & test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-targets: false

    - name: Install Just
      run: cargo install just

    - name: Install Nextest
      uses: taiki-e/install-action@nextest

    - name: 🔨 Run formatting check
      run: cargo fmt --all -- --check

    - name: 🚀 Run build
      run: RUST_BACKTRACE=1 just build

    - name: 🔨 Run clippy check
      # No color output for problem matcher to capture
      run: |
        echo "::add-matcher::.github/rust-problems.json"
        just clippy-no-color
        echo "::remove-matcher owner=rust-compiler::"
        echo "::remove-matcher owner=rust-fmt::"
        echo "::remove-matcher owner=rust-panic::"

    - name: 🔨 Run docs generator
      run: |
        echo "::add-matcher::.github/rust-problems.json"
        just doc-no-color
        echo "::remove-matcher owner=rust-compiler::"
        echo "::remove-matcher owner=rust-fmt::"
        echo "::remove-matcher owner=rust-panic::"

    - name: 🚦 Run tests
      run: RUST_BACKTRACE=1 RUST_LOG=trace just test
